server:
  port: 8080

spring:
  #  mvc:
  #    view:
  #      prefix: /WEB-INF/views
  #      suffix: .jsp
  #  messages:
  #    basename: errors,messages
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    cache: false

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: jisun
    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: oracle
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.Oracle12cDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


#mybatis:
#  config-location:  classpath:mapper/config/config.xml
#  mapper-locations: classpath:mapper/sql/**/*.xml
  #type-aliases-package: com.jisun.gallery.dto

file:
  path: C:/upload/
