server:
  port: 8080

spring:
  #  mvc:
  #    view:
  #      prefix: /WEB-INF/views
  #      suffix: .jsp
  #  messages:
  #    basename: errors,messages
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    cache: false

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: jisun
    password: 1234

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  mail:
    host: smtp.naver.com
    port: 465
    username: snm03097@naver.com
    password: luckyzzang0109
    properties:
      debug: true
      mail:
        smtp:
          auth: true
          ssl:
            enabled: true
            trust: smtp.naver.com
    protocol: smtps

mybatis:
  config-location:  classpath:mapper/config/config.xml
  mapper-locations: classpath:mapper/sql/**/*.xml
  #type-aliases-package: com.jisun.gallery.dto

file:
  path: C:/upload/
